In [6]:
import pandas as pd

# Загрузка файла
df = pd.read_csv('ml_dataset_20k.csv')

# Первые 5 строк
df.head()

# Последние 5 строк
df.tail()

# Размер датасета (строки, столбцы)
df.shape

# Названия столбцов
df.columns

# Типы данных
df.dtypes

# Общая инфо о датасете
df.info()

# Статистика (среднее, мин, макс...)
df.describe()

# Кол-во пропущенных значений
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5938 entries, 0 to 5937
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   incident_id                   5938 non-null   int64
 1   probability                   5938 non-null   int64
 2   is_real_incident              5938 non-null   int64
 3   last_order_end                5938 non-null   object
 4   after_order_start             5938 non-null   object
 5   gap_minutes                   5938 non-null   float64
 6   total_after_distance_km       5938 non-null   float64
 7   max_jump_distance_km          5938 non-null   float64
 8   mean_speed_kmh                5938 non-null   float64
 9   median_speed_kmh              5938 non-null   float64
 10  max_speed_kmh                 5938 non-null   float64
 11  bearing_changes               5938 non-null   int64
 12  static_segments_ratio         5938 non-null   float64
 13  radius_from_start_m           5938 non-null   float64
 14  coordinate_stability_m        5938 non-null   float64
 15  return_count                  5938 non-null   int64
 16  after_order_start_hour        5938 non-null   int64
 17  after_track_duration_minutes  5938 non-null   float64
 18  bearing_changes_ratio         5938 non-null   float64
 19  full_stop_count               5938 non-null   int64
 20  linearity                     5938 non-null   float64
dtypes: float64(12), int64(7), object(2)
memory usage: 974.3+ KB

incident_id                     0
probability                     0
is_real_incident                0
last_order_end                  0
after_order_start               0
gap_minutes                     0
total_after_distance_km         0
max_jump_distance_km            0
mean_speed_kmh                  0
median_speed_kmh                0
max_speed_kmh                   0
bearing_changes                 0
static_segments_ratio           0
radius_from_start_m             0
coordinate_stability_m          0
return_count                    0
after_order_start_hour          0
after_track_duration_minutes    0
bearing_changes_ratio           0
full_stop_count                 0
linearity                       0
dtype: int64

In [7]:
# Ячейка 1
import pandas as pd
df = pd.read_csv('ml_dataset_20k.csv')

In [8]:
# Ячейка 2
df.head(10)

,incident_id,probability,is_real_incident,last_order_end,after_order_start,gap_minutes,total_after_distance_km,max_jump_distance_km,mean_speed_kmh,median_speed_kmh,max_speed_kmh,bearing_changes,static_segments_ratio,radius_from_start_m,coordinate_stability_m,return_count,after_order_start_hour,after_track_duration_minutes,bearing_changes_ratio,full_stop_count,linearity
0,25744,70,0,0001-01-01T00:00:00,2025-03-10T01:12:28.299000,1064619432.47,1.12,0.14,0.08,0.04,5.09,147,0.99,355.60,68.09,482,1,1087.73,0.25,561,0.32
1,25743,0,0,0001-01-01T00:00:00,2025-03-10T18:12:55.712000,1064620452.93,0.02,0.00,0.46,0.02,16.04,13,0.97,2.55,0.91,36,18,67.21,0.36,34,0.11
2,25741,70,0,0001-01-01T00:00:00,2025-03-10T16:36:27.604000,1064620356.46,2.63,0.57,37.35,0.18,2999.62,11,0.78,807.81,227.19,46,16,162.25,0.13,65,0.03
3,25740,70,0,0001-01-01T00:00:00,2025-03-10T12:00:00.595000,1064620080.01,5.90,0.49,0.90,0.26,14.36,33,0.87,435.53,131.13,141,12,437.85,0.17,171,0.01
4,25739,0,0,0001-01-01T00:00:00,2025-03-10T19:06:51.672000,1064620506.86,0.25,0.24,74.77,0.16,596.49,4,0.88,239.35,74.19,0,19,8.06,0.57,4,0.95
5,25738,70,0,0001-01-01T00:00:00,2025-03-10T18:58:01.695000,1064620498.03,4.22,1.38,10.62,1.90,47.37,2,0.50,3957.90,1511.35,2,18,16.86,0.15,3,0.94
6,25737,0,0,0001-01-01T00:00:00,2025-03-10T19:05:33.818000,1064620505.56,0.00,0.00,0.00,0.00,0.00,0,1.00,0.00,0.00,4,19,7.71,0.00,4,0.00
7,25735,0,0,0001-01-01T00:00:00,2025-03-10T19:05:54.051000,1064620505.90,0.00,0.00,3.21,0.00,31.78,2,0.90,0.74,0.29,9,19,4.93,0.22,3,0.15
8,25734,0,0,0001-01-01T00:00:00,2025-03-10T18:25:58.365000,1064620465.97,111.94,25.77,166.89,127.03,776.00,2,0.25,25773.86,14693.68,0,18,42.91,0.10,5,0.01
9,25733,70,1,0001-01-01T00:00:00,2025-03-10T16:36:27.604000,1064620356.46,1.94,0.27,39.42,0.13,2999.62,11,0.79,807.81,209.40,44,16,152.24,0.14,62,0.39

In [9]:
# Ячейка 3
df.describe().round(2)

,incident_id,probability,is_real_incident,gap_minutes,total_after_distance_km,max_jump_distance_km,mean_speed_kmh,median_speed_kmh,max_speed_kmh,bearing_changes,static_segments_ratio,radius_from_start_m,coordinate_stability_m,return_count,after_order_start_hour,after_track_duration_minutes,bearing_changes_ratio,full_stop_count,linearity
count,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00,5938.00
mean,22135.11,19.68,0.10,1064617765.00,537.55,63.97,5146.01,88.77,434256.80,25.54,0.71,63308.78,11920.29,98.20,14.67,363.61,0.17,145.54,0.33
std,2109.70,28.83,0.30,1247.90,2376.51,566.37,171000.69,4105.05,19282092.92,43.42,0.31,566372.74,111932.64,201.47,5.57,503.56,0.19,228.65,0.37
min,18161.00,0.00,0.00,1064614141.22,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,20486.25,0.00,0.00,1064617004.48,0.21,0.08,0.26,0.00,7.82,1.00,0.50,148.83,28.06,2.00,12.00,11.27,0.03,3.00,0.01
50%,22192.50,0.00,0.00,1064617591.31,3.32,0.84,3.78,0.03,59.48,7.00,0.83,1181.05,306.30,8.00,16.00,130.15,0.12,24.00,0.12
75%,23935.75,45.00,0.00,1064618716.38,235.08,30.49,94.59,2.14,1490.99,31.00,0.98,30759.78,8982.69,93.00,18.00,514.40,0.24,198.00,0.67
max,25744.00,75.00,1.00,1064620506.86,77653.09,8347.68,7981809.75,281538.46,1251772296.73,456.00,1.00,8345132.17,3736607.19,2582.00,23.00,2157.34,1.00,1247.00,1.00

In [10]:
# Ячейка 4
df[['probability', 'gap_minutes', 'mean_speed_kmh', 'max_speed_kmh']].head(10)

   probability   gap_minutes  mean_speed_kmh  max_speed_kmh
0           70 1064619432.47            0.08           5.09
1            0 1064620452.93            0.46          16.04
2           70 1064620356.46           37.35        2999.62
3           70 1064620080.01            0.90          14.36
4            0 1064620506.86           74.77         596.49
5           70 1064620498.03           10.62          47.37
6            0 1064620505.56            0.00           0.00
7            0 1064620505.90            3.21          31.78
8            0 1064620465.97          166.89         776.00
9           70 1064620356.46           39.42        2999.62

In [11]:
# Ячейка 5
df.isnull().sum()

incident_id                     0
probability                     0
is_real_incident                0
last_order_end                  0
after_order_start               0
gap_minutes                     0
total_after_distance_km         0
max_jump_distance_km            0
mean_speed_kmh                  0
median_speed_kmh                0
max_speed_kmh                   0
bearing_changes                 0
static_segments_ratio           0
radius_from_start_m             0
coordinate_stability_m          0
return_count                    0
after_order_start_hour          0
after_track_duration_minutes    0
bearing_changes_ratio           0
full_stop_count                 0
linearity                       0
dtype: int64